backend:
  name: git-gateway
  repo: https://github.com/LasseKrarup/ember-music-collective
  branch: main

local_backend: true

media_folder: static/img
public_folder: /img

media_library:
  name: cloudinary
  config:
    cloud_name: embermusic-dk
    api_key: 871611657891839
    multiple: true

# Disables preview editor
editor:
  preview: false

# Collections
# https://www.netlifycms.org/docs/collection-types/
collections:
  - name: "program"
    label: "Emberfest Program"
    label_singular: "Emberfest Artist"
    folder: "content/pages/program"
    path: "{{slug}}/index"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Show start", name: "showstart", widget: "datetime", date_format: "DD. MMMM YYYY", time_format: "HH:mm", default: "", required: false }
      - { label: "Tag line (short description)", name: "description", widget: "string" }
      - label: "Image"
        name: "image"
        widget: "image"
        media_library:
          config:
            multiple: false
      - { label: "Bio", name: "body", widget: "markdown" }
